### ISSUE TITLE
Verify version, documentation, license, URL, recipe, build

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-notebook#110]
Go through all Notebook-associated repos and verify the following are sufficient:

* `README.md` is meaningful and informative
* `LICENSE.txt` is correct (BSD for OSS, our proprietary license for the rest)
* `.binstar.yml` is correct and Anaconda Cloud CI configured
* `conda.recipe` has the correct name, version, URL, license
* `setup.py` (there are two of them now!) are correct

This needs to be done for all the repos in this work stream:

* [x] `anaconda-notebook`
* [x] `nbwrapper` (inside the `anaconda-notebook` repo)
* [x] `nbsetuptools`
* [x] `nb_helloworld`
* [x] `nbbrowserpdf`
* [x] `nbpresent`
* [x] `generator-nbextension`
* [x] `nb_locker`
* [x] `nb_conda`
* [x] `nb_revisioncontrol`
* [x] `nb_conda_kernels`

**Comment by malev** [comment]
I've checked `nbsetuptools`, `nb_helloworld` and `generator-nbextension`

**Comment by ijstokes** [comment]
I've checked `anaconda-notebook`, `nbpresent`, and `nbbrowserpdf` and they're all looking fine.  Some of the `README` content could do with some wordsmithing and a tidy up, but they're good enough for now.
