### ISSUE TITLE
Prototype Jupyter server extension

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-notebook#18]
Take the work done in #14 and generalize it into a "hello world"-style extension. Should illustrate how communication works between the notebook client and server. 

Scope of the extension is: 
- graphical button
- back-end integration
- config
- installation & testing

Success Critiera
* [x] Build a simple jupyter server extension to locking function
* [ ] Package it up for easy installation  --> Conda Install "X"
* [ ] Write the appropriate readme documentation --> should appear in repo

**Comment by ijstokes** [comment]
@malev I just tried `conda create -n nbext_helloworld` -c anaconda-notebook nb_helloworld` but no luck.  I don't know what to look for to see what the *"hello world" actually encapsulates, but I can't see any evidence of it running.  I wanted to 'figure it out for myself" how ever I did not see any evidence of any "Hello World" extension.

**Comment by mmarchetti** [comment]
We haven't built packages for nb_helloworld yet. I just did the internal package renaming, and will build packages and open a PR.

**Comment by mmarchetti** [comment]
I just built and uploaded packaged for nb_helloworld on the anaconda-notebook channel.

**Comment by damianavila** [comment]
As far as I know this is completed by https://github.com/Anaconda-Server/nb_helloworld/pull/3, closing here now.
