### ISSUE TITLE
Create skeleton conda recipe for a single extension

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-notebook#19]
Goal: drive adoption of conda packages as the delivery mechanism for notebook extensions

Success Criteria:
- [x] templated meta.yml
- [x] build scripts
- [x] pre- and post-link scripts 
- [x] upload to public location
- [ ] ~~brief blog post on how to use this to create exposure~~ deferred to blog post #99

**Comment by ijstokes** [comment]
This was completed by @malev as part of #89
