### ISSUE TITLE
Conda Environments (syncer) should be made a server extension

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-notebook#34]
From inside a notebook, change which `conda` environment is in use. Has implications for available kernels. This probably includes a combination of new menu item *Conda*:
* select (from available list) (`conda info -a`) and activate (`source activate foo`)

**Comment by ijstokes** [comment]
@damianavila is having internet connection issues right now but reports that this work is basically done and just needs to be committed to the newly created repo https://github.com/Anaconda-Server/nb_conda_kernels

**Comment by damianavila** [comment]
PRs for this one: 

* https://github.com/Anaconda-Server/nb_conda_kernels/pull/1
* https://github.com/Anaconda-Server/anaconda-notebook/pull/107

**Comment by damianavila** [comment]
Both PRs merged, closing here.
