### ISSUE TITLE
Conda recipe and builds for each of the extensions

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Server/anaconda-notebook#57]
This is for later, but eventually we need to have conda packages for each extension and make a metapackage to join them to the rest of the anaconda notebook (wrappers).

* [X] Meta Anaconda Notebook package
* [X] Locker
* [X] Conda Env
* [x] RCM #36 needs to be completed first
* [x] nbwrapper (in a pr)
* [ ] Syncer #34 needs to be completed first

**Comment by ijstokes** [comment]
@damianavila has said a conda recipe will be created as part of the refactoring of "syncer" into a kernel manager, so this story can be closed.
