### ISSUE TITLE
Refactor Repositories to address open source vs. proprietary repos

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-notebook#85]
Proprietary: 
* [x] Revision control
* [x] Notebook locking

Open Source: 
* [x] wrapper (to setup environment variables and directories required by conda-encapsulated extension)
* [x] nbsetuptools (shared extension install/enable/disable mechanics)
* [x] generator-nbextension
* [x] hello world extension
* [ ] syncer (now not an extension but a kernel manager)
* [x] conda extension to provide in-notebook access to conda operations

**Comment by ijstokes** [comment]
Syncer is being significantly reorganized by @damianavila and is now the only outstanding piece for this to be closed.

**Comment by ijstokes** [comment]
@damianavila has said he will look after "syncer" as part of completing that work, so this story is closed.
