### ISSUE TITLE
Automated building of all extension packages on Anaconda Cloud

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/anaconda-notebook#89]
#33 provided a "first pass" at a `.binstar.yml` build file (which worked) and this is a follow on story to get it working for all extensions on all platforms for all (relevant) Python versions.

We need to provide as many of these extensions as are available for the platform/python-version pair:

* [x] condaenvs
* [ ] syncer
* [x] locker (private repo and private Anaconda Cloud package)
* [x] rcm (private repo and private Anaconda Cloud package)
* [ ] nbpresent
* [x] nbwrapper
* [ ] nbbrowserpdf

These should be available for as many of these platforms as possible:

* [x] linux 64
* [x] os x
* [ ] windows 64

with support for Python versions:

* [x] Python 2.7
* [x] Python 3.4
* [x] Python 3.5

The meta-package `anaconda-notebook` **should not** include `locker` or `rcm` as dependencies as these are going to be proprietary.

There are additional requirements on this story:

* [ ] each extension needs to be built automatically by Anaconda Build
       * so subsequent updates to the extension will automatically create a conda package in the same way
* [x] each extension needs to make use of the `nbsetuptools` package #82 and #90
* [x] each extension needs to come from its own repository #85

**Comment by malev** [comment]
@mmarchetti can you take a look at https://anaconda.org/anaconda-notebook/anaconda-notebook/builds/140/1 ?

**Comment by mmarchetti** [comment]
We are blocked on this by https://github.com/Anaconda-Server/anaconda-client/issues/222 (OS X workers can't upload built packages) and https://github.com/Anaconda-Server/anaconda-build/issues/150 (win64 workers can't build on python 2.7)

**Comment by mmarchetti** [comment]
Core extensions that we plan to ship with Anaconda should also be built for win-32 and linux-32.
