### ISSUE TITLE
Refactor all extensions to use nbsetuptools

### ISSUE THREAD

**Issue by mmarchetti** [Anaconda-Server/anaconda-notebook#95]
Convert all existing extensions to use `nbsetuptools rather than the current copy-and-paste of template code (`install` sub-module and other functions).

* [ ] nbpresent
* [x] rcm
* [x] locker
* [ ] ~~syncer~~
* [x] condaenvs

Eliminate the boilerplate `install.py` and `setup.py` and replace with `nbsetuptools` calls.

Ensure that `pre-unlink` scripts exist so the extensions can be disabled in Jupyter config files before they are uninstalled.

**Comment by mmarchetti** [comment]
@ijstokes @bollwyvl I would like to get your input on whether it makes sense to switch nbpresent over to using the nbsetuptools infrastructure at this point. I have done the work to enable it in a local branch, so it's not a matter of effort. My concern is that nbpresent is a publicly-available package on PyPI already, while nbsetuptools and nbwrapper (which will now be introduced as dependencies) are not.

I propose we defer this work and create a new issue to track it. In the meantime, I can push my branch so we don't lose the invested work.

**Comment by bollwyvl** [comment]
> I propose we defer this work and create a new issue to track it. In the meantime, I can push my branch so we don't lose the invested work. 

agreed: i'd love to use nbsetuptools, but that's the rub of open source. Related to this, mentioned last week:

https://github.com/jupyter/enhancement-proposals/pull/7

and of course @malev https://github.com/Anaconda-Server/generator-nbextension

Keep me posted when/if the decision is made whether to release nbsetuptools or generator as open source. I think we've put a really good foundation down here, but to have a broad impact, we'll want to get them broadly adopted... and community feedback is invaluable. There's already some great links to check out there. We should definitely get the KernelSpecManager listed that did conda envs.

Anhow, if both of those are open sourced, I think that could even be _another_ blog post, on more of an engineering channel.

There's a ton of interest on building extensions as higher quality software. Being able to install it is key to test it (as we've learned), as is being able to support the testing matrix on anaconda.org, i.e.
```
engine:
  - python=2.7 jupyter=4
  - python=2.7 jupyter=5
  - python=3.4 jupyter=4
  - python=3.4 jupyter=5
  - python=3.5 jupyter=4
  - python=3.5 jupyter=5
```
(i am sure could be made more concise with jinja magic)

would be an amazing motivator to use conda/anaconda.org, as a means to the veracity of a development process. very exciting stuff!

**Comment by ijstokes** [comment]
I've created #104 and #105 to capture the follow on work for `nbpresent`, and all these "foundational" pieces are MIT licensed.  Closing this issue.
